webpackJsonp(["review-fullpage.module"],{

/***/ "../../../../../src/app/component/fullpage/fullpage.component.ngfactory.js":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* unused harmony export FullpageModuleNgFactory */
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "b", function() { return RenderType_FullpageSlideComponent; });
/* harmony export (immutable) */ __webpack_exports__["d"] = View_FullpageSlideComponent_0;
/* unused harmony export View_FullpageSlideComponent_Host_0 */
/* unused harmony export FullpageSlideComponentNgFactory */
/* unused harmony export RenderType_FullpageBulletComponent */
/* unused harmony export View_FullpageBulletComponent_0 */
/* unused harmony export View_FullpageBulletComponent_Host_0 */
/* unused harmony export FullpageBulletComponentNgFactory */
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return RenderType_FullpageComponent; });
/* harmony export (immutable) */ __webpack_exports__["c"] = View_FullpageComponent_0;
/* unused harmony export View_FullpageComponent_Host_0 */
/* unused harmony export FullpageComponentNgFactory */
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__("../../../core/esm5/core.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__fullpage_component__ = __webpack_require__("../../../../../src/app/component/fullpage/fullpage.component.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__angular_common__ = __webpack_require__("../../../common/esm5/common.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__common_dom__ = __webpack_require__("../../../../../src/app/component/common/dom.ts");
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 




var FullpageModuleNgFactory = __WEBPACK_IMPORTED_MODULE_0__angular_core__["_12" /* ɵcmf */](__WEBPACK_IMPORTED_MODULE_1__fullpage_component__["c" /* FullpageModule */], [], function (_l) { return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_26" /* ɵmod */]([__WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](512, __WEBPACK_IMPORTED_MODULE_0__angular_core__["k" /* ComponentFactoryResolver */], __WEBPACK_IMPORTED_MODULE_0__angular_core__["_8" /* ɵCodegenComponentFactoryResolver */], [[8, []], [3, __WEBPACK_IMPORTED_MODULE_0__angular_core__["k" /* ComponentFactoryResolver */]], __WEBPACK_IMPORTED_MODULE_0__angular_core__["E" /* NgModuleRef */]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](4608, __WEBPACK_IMPORTED_MODULE_2__angular_common__["l" /* NgLocalization */], __WEBPACK_IMPORTED_MODULE_2__angular_common__["k" /* NgLocaleLocalization */], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["A" /* LOCALE_ID */], [2, __WEBPACK_IMPORTED_MODULE_2__angular_common__["t" /* ɵa */]]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](512, __WEBPACK_IMPORTED_MODULE_2__angular_common__["b" /* CommonModule */], __WEBPACK_IMPORTED_MODULE_2__angular_common__["b" /* CommonModule */], []), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](512, __WEBPACK_IMPORTED_MODULE_1__fullpage_component__["c" /* FullpageModule */], __WEBPACK_IMPORTED_MODULE_1__fullpage_component__["c" /* FullpageModule */], [])]); });

var styles_FullpageSlideComponent = [];
var RenderType_FullpageSlideComponent = __WEBPACK_IMPORTED_MODULE_0__angular_core__["_13" /* ɵcrt */]({ encapsulation: 2, styles: styles_FullpageSlideComponent, data: {} });

function View_FullpageSlideComponent_0(_l) { return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_38" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n    "])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_15" /* ɵeld */](1, 0, null, null, 5, "div", [["class", "free-fullpage-slide"]], [[4, "height", "px"]], null, null, null, null)), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_14" /* ɵdid */](2, 278528, null, 0, __WEBPACK_IMPORTED_MODULE_2__angular_common__["h" /* NgClass */], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["y" /* IterableDiffers */], __WEBPACK_IMPORTED_MODULE_0__angular_core__["z" /* KeyValueDiffers */], __WEBPACK_IMPORTED_MODULE_0__angular_core__["n" /* ElementRef */], __WEBPACK_IMPORTED_MODULE_0__angular_core__["M" /* Renderer2 */]], { klass: [0, "klass"], ngClass: [1, "ngClass"] }, null), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_32" /* ɵpod */](3, { "free-fullpage-slide-active": 0 }), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n      "])), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_28" /* ɵncd */](null, 0), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n    "])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n  "]))], function (_ck, _v) { var _co = _v.component; var currVal_1 = "free-fullpage-slide"; var currVal_2 = _ck(_v, 3, 0, _co.active); _ck(_v, 2, 0, currVal_1, currVal_2); }, function (_ck, _v) { var _co = _v.component; var currVal_0 = _co.height; _ck(_v, 1, 0, currVal_0); }); }
function View_FullpageSlideComponent_Host_0(_l) { return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_38" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_15" /* ɵeld */](0, 0, null, null, 1, "free-fullpage-slide", [], null, null, null, View_FullpageSlideComponent_0, RenderType_FullpageSlideComponent)), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_14" /* ɵdid */](1, 49152, null, 0, __WEBPACK_IMPORTED_MODULE_1__fullpage_component__["d" /* FullpageSlideComponent */], [__WEBPACK_IMPORTED_MODULE_1__fullpage_component__["b" /* FullpageComponent */]], null, null)], null, null); }
var FullpageSlideComponentNgFactory = __WEBPACK_IMPORTED_MODULE_0__angular_core__["_11" /* ɵccf */]("free-fullpage-slide", __WEBPACK_IMPORTED_MODULE_1__fullpage_component__["d" /* FullpageSlideComponent */], View_FullpageSlideComponent_Host_0, { index: "index" }, {}, ["*"]);

var styles_FullpageBulletComponent = [];
var RenderType_FullpageBulletComponent = __WEBPACK_IMPORTED_MODULE_0__angular_core__["_13" /* ɵcrt */]({ encapsulation: 2, styles: styles_FullpageBulletComponent, data: {} });

function View_FullpageBulletComponent_0(_l) { return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_38" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n    "])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_15" /* ɵeld */](1, 0, null, null, 2, "div", [["class", "free-pagination-bullet"]], null, null, null, null, null)), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_14" /* ɵdid */](2, 278528, null, 0, __WEBPACK_IMPORTED_MODULE_2__angular_common__["h" /* NgClass */], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["y" /* IterableDiffers */], __WEBPACK_IMPORTED_MODULE_0__angular_core__["z" /* KeyValueDiffers */], __WEBPACK_IMPORTED_MODULE_0__angular_core__["n" /* ElementRef */], __WEBPACK_IMPORTED_MODULE_0__angular_core__["M" /* Renderer2 */]], { klass: [0, "klass"], ngClass: [1, "ngClass"] }, null), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_32" /* ɵpod */](3, { "free-pagination-bullet-active": 0 }), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n  "]))], function (_ck, _v) { var _co = _v.component; var currVal_0 = "free-pagination-bullet"; var currVal_1 = _ck(_v, 3, 0, _co.active); _ck(_v, 2, 0, currVal_0, currVal_1); }, null); }
function View_FullpageBulletComponent_Host_0(_l) { return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_38" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_15" /* ɵeld */](0, 0, null, null, 1, "free-pagination-bullet", [], null, null, null, View_FullpageBulletComponent_0, RenderType_FullpageBulletComponent)), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_14" /* ɵdid */](1, 49152, null, 0, __WEBPACK_IMPORTED_MODULE_1__fullpage_component__["a" /* FullpageBulletComponent */], [], null, null)], null, null); }
var FullpageBulletComponentNgFactory = __WEBPACK_IMPORTED_MODULE_0__angular_core__["_11" /* ɵccf */]("free-pagination-bullet", __WEBPACK_IMPORTED_MODULE_1__fullpage_component__["a" /* FullpageBulletComponent */], View_FullpageBulletComponent_Host_0, { index: "index", active: "active" }, {}, []);

var styles_FullpageComponent = [];
var RenderType_FullpageComponent = __WEBPACK_IMPORTED_MODULE_0__angular_core__["_13" /* ɵcrt */]({ encapsulation: 2, styles: styles_FullpageComponent, data: {} });

function View_FullpageComponent_2(_l) { return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_38" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_15" /* ɵeld */](0, 0, null, null, 2, "free-pagination-bullet", [], null, [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.onPaginationClick(_v.context.index) !== false);
        ad = (pd_0 && ad);
    } return ad; }, View_FullpageBulletComponent_0, RenderType_FullpageBulletComponent)), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_14" /* ɵdid */](1, 49152, null, 0, __WEBPACK_IMPORTED_MODULE_1__fullpage_component__["a" /* FullpageBulletComponent */], [], { index: [0, "index"], active: [1, "active"] }, null), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n        "]))], function (_ck, _v) { var _co = _v.component; var currVal_0 = _v.context.index; var currVal_1 = (_co.activeIndex === _v.context.index); _ck(_v, 1, 0, currVal_0, currVal_1); }, null); }
function View_FullpageComponent_1(_l) { return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_38" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_15" /* ɵeld */](0, 0, [[3, 0], ["pagination", 1]], null, 4, "div", [["class", "free-fullpage-pagination"]], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n        "])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_10" /* ɵand */](16777216, null, null, 1, null, View_FullpageComponent_2)), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_14" /* ɵdid */](3, 802816, null, 0, __WEBPACK_IMPORTED_MODULE_2__angular_common__["i" /* NgForOf */], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["Y" /* ViewContainerRef */], __WEBPACK_IMPORTED_MODULE_0__angular_core__["V" /* TemplateRef */], __WEBPACK_IMPORTED_MODULE_0__angular_core__["y" /* IterableDiffers */]], { ngForOf: [0, "ngForOf"] }, null), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n      "]))], function (_ck, _v) { var _co = _v.component; var currVal_0 = _co.slides; _ck(_v, 3, 0, currVal_0); }, null); }
function View_FullpageComponent_0(_l) { return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_38" /* ɵvid */](0, [__WEBPACK_IMPORTED_MODULE_0__angular_core__["_34" /* ɵqud */](402653184, 1, { containerViewChild: 0 }), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_34" /* ɵqud */](402653184, 2, { wrapperViewChild: 0 }), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_34" /* ɵqud */](671088640, 3, { paginationViewChild: 0 }), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n    "])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_15" /* ɵeld */](4, 0, [[1, 0], ["container", 1]], null, 9, "div", [["class", "free-fullpage-container"]], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n      "])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_15" /* ɵeld */](6, 0, [[2, 0], ["wrapper", 1]], null, 3, "div", [["class", "free-fullpage-wrapper"]], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n        "])), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_28" /* ɵncd */](null, 0), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n      "])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n      "])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_10" /* ɵand */](16777216, null, null, 1, null, View_FullpageComponent_1)), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_14" /* ɵdid */](12, 16384, null, 0, __WEBPACK_IMPORTED_MODULE_2__angular_common__["j" /* NgIf */], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["Y" /* ViewContainerRef */], __WEBPACK_IMPORTED_MODULE_0__angular_core__["V" /* TemplateRef */]], { ngIf: [0, "ngIf"] }, null), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n    "])), (_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_36" /* ɵted */](-1, null, ["\n  "]))], function (_ck, _v) { var _co = _v.component; var currVal_0 = _co.pagination; _ck(_v, 12, 0, currVal_0); }, null); }
function View_FullpageComponent_Host_0(_l) { return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_38" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_15" /* ɵeld */](0, 0, null, null, 2, "free-fullpage", [], null, [["window", "resize"], ["document", "wheel"]], function (_v, en, $event) { var ad = true; if (("window:resize" === en)) {
        var pd_0 = (__WEBPACK_IMPORTED_MODULE_0__angular_core__["_29" /* ɵnov */](_v, 2).onResize() !== false);
        ad = (pd_0 && ad);
    } if (("document:wheel" === en)) {
        var pd_1 = (__WEBPACK_IMPORTED_MODULE_0__angular_core__["_29" /* ɵnov */](_v, 2).onWheel($event) !== false);
        ad = (pd_1 && ad);
    } return ad; }, View_FullpageComponent_0, RenderType_FullpageComponent)), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_33" /* ɵprd */](512, null, __WEBPACK_IMPORTED_MODULE_3__common_dom__["a" /* DomRenderer */], __WEBPACK_IMPORTED_MODULE_3__common_dom__["a" /* DomRenderer */], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["M" /* Renderer2 */]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_14" /* ɵdid */](2, 4374528, null, 0, __WEBPACK_IMPORTED_MODULE_1__fullpage_component__["b" /* FullpageComponent */], [__WEBPACK_IMPORTED_MODULE_3__common_dom__["a" /* DomRenderer */]], null, null)], null, null); }
var FullpageComponentNgFactory = __WEBPACK_IMPORTED_MODULE_0__angular_core__["_11" /* ɵccf */]("free-fullpage", __WEBPACK_IMPORTED_MODULE_1__fullpage_component__["b" /* FullpageComponent */], View_FullpageComponent_Host_0, { pagination: "pagination", paginationClickable: "paginationClickable" }, { slideStart: "slideStart", slideEnd: "slideEnd" }, ["*"]);



/***/ }),

/***/ "../../../../../src/app/component/fullpage/fullpage.component.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "d", function() { return FullpageSlideComponent; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return FullpageBulletComponent; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "b", function() { return FullpageComponent; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "c", function() { return FullpageModule; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__("../../../core/esm5/core.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__common_dom__ = __webpack_require__("../../../../../src/app/component/common/dom.ts");


var FullpageSlideComponent = (function () {
    function FullpageSlideComponent(group) {
        this.group = group;
        this.group.addSlide(this);
    }
    return FullpageSlideComponent;
}());

var FullpageBulletComponent = (function () {
    function FullpageBulletComponent() {
    }
    return FullpageBulletComponent;
}());

var FullpageComponent = (function () {
    function FullpageComponent(domRenderer) {
        this.domRenderer = domRenderer;
        this.slideStart = new __WEBPACK_IMPORTED_MODULE_0__angular_core__["p" /* EventEmitter */]();
        this.slideEnd = new __WEBPACK_IMPORTED_MODULE_0__angular_core__["p" /* EventEmitter */]();
        this.activeIndex = 0;
        this.win = {
            width: window.innerWidth,
            height: window.innerHeight
        };
        this.slides = [];
    }
    FullpageComponent.prototype.onResize = function () {
        this.win = {
            width: window.innerWidth,
            height: window.innerHeight
        };
    };
    FullpageComponent.prototype.onWheel = function (e) {
        e = e || window.event;
        if (!this.isScroll) {
            if (e.wheelDelta) {
                if (e.wheelDelta > 0) {
                    this.scrollPrev();
                }
                else if (e.wheelDelta < 0) {
                    this.scrollNext();
                }
            }
            else if (e.detail) {
                if (e.detail < 0) {
                    this.scrollPrev();
                }
                else if (e.detail > 0) {
                    this.scrollNext();
                }
            }
        }
    };
    FullpageComponent.prototype.addSlide = function (slide) {
        this.slides.push(slide);
    };
    FullpageComponent.prototype.ngAfterViewInit = function () {
        var _this = this;
        this.container = this.containerViewChild.nativeElement;
        this.wrapper = this.wrapperViewChild.nativeElement;
        if (this.pagination) {
            this.paginationElem = this.paginationViewChild.nativeElement;
        }
        this.refreshView();
        this.transitionstartListener = this.domRenderer.listen(this.wrapper, 'transitionstart', function () {
            if (_this.container) {
                _this.isScroll = true;
                _this.slideStart.emit({
                    activeIndex: _this.activeIndex
                });
            }
        });
        this.transitionendListerner = this.domRenderer.listen(this.wrapper, 'transitionend', function () {
            if (_this.container) {
                _this.isScroll = false;
                _this.slideEnd.emit({
                    activeIndex: _this.activeIndex
                });
            }
        });
    };
    FullpageComponent.prototype.onPaginationClick = function (index) {
        if (this.paginationClickable) {
            this.scrollTo(index);
        }
    };
    FullpageComponent.prototype.refreshView = function () {
        var wHeight = this.win['height'];
        this.totalSlides = this.slides.length;
        this.wrapper.style.height = wHeight * this.totalSlides + 'px';
        for (var _i = 0, _a = this.slides; _i < _a.length; _i++) {
            var slide = _a[_i];
            slide.height = wHeight;
        }
    };
    FullpageComponent.prototype.scrollPrev = function () {
        if (this.activeIndex > 0) {
            this.activeIndex--;
            this.scrollTo(this.activeIndex);
        }
    };
    FullpageComponent.prototype.scrollNext = function () {
        if (this.activeIndex < this.totalSlides - 1) {
            this.activeIndex++;
            this.scrollTo(this.activeIndex);
        }
    };
    FullpageComponent.prototype.scrollTo = function (index) {
        if (index < this.totalSlides) {
            this.isScroll = true;
            this.wrapper.style.transform = 'translate3d(0,-' + this.win['height'] * index + 'px,0)';
            this.activeIndex = index;
        }
    };
    FullpageComponent.prototype.ngOnDestroy = function () {
        if (this.transitionstartListener) {
            this.transitionstartListener();
        }
        if (this.transitionendListerner) {
            this.transitionendListerner();
        }
        this.container = null;
    };
    return FullpageComponent;
}());

var FullpageModule = (function () {
    function FullpageModule() {
    }
    return FullpageModule;
}());



/***/ }),

/***/ "../../../../../src/app/democase/main-fullpage/main-fullpage.component.scss.shim.ngstyle.js":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return styles; });
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["[_nghost-%COMP%]     .fullpage, [_nghost-%COMP%]     .fullpage img {\n  display: block;\n  width: 100%;\n  height: 100%; }"];



/***/ }),

/***/ "../../../../../src/app/democase/main-fullpage/review-fullpage-routing.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return ReviewFullpageRoutingModule; });
var ReviewFullpageRoutingModule = (function () {
    function ReviewFullpageRoutingModule() {
    }
    return ReviewFullpageRoutingModule;
}());



/***/ }),

/***/ "../../../../../src/app/democase/main-fullpage/review-fullpage.component.ngfactory.js":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* unused harmony export RenderType_ReviewFullpageComponent */
/* unused harmony export View_ReviewFullpageComponent_0 */
/* unused harmony export View_ReviewFullpageComponent_Host_0 */
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return ReviewFullpageComponentNgFactory; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__main_fullpage_component_scss_shim_ngstyle__ = __webpack_require__("../../../../../src/app/democase/main-fullpage/main-fullpage.component.scss.shim.ngstyle.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__angular_core__ = __webpack_require__("../../../core/esm5/core.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__component_fullpage_fullpage_component_ngfactory__ = __webpack_require__("../../../../../src/app/component/fullpage/fullpage.component.ngfactory.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__component_common_dom__ = __webpack_require__("../../../../../src/app/component/common/dom.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__ = __webpack_require__("../../../../../src/app/component/fullpage/fullpage.component.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__review_fullpage_component__ = __webpack_require__("../../../../../src/app/democase/main-fullpage/review-fullpage.component.ts");
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 






var styles_ReviewFullpageComponent = [__WEBPACK_IMPORTED_MODULE_0__main_fullpage_component_scss_shim_ngstyle__["a" /* styles */]];
var RenderType_ReviewFullpageComponent = __WEBPACK_IMPORTED_MODULE_1__angular_core__["_13" /* ɵcrt */]({ encapsulation: 0, styles: styles_ReviewFullpageComponent, data: {} });

function View_ReviewFullpageComponent_0(_l) { return __WEBPACK_IMPORTED_MODULE_1__angular_core__["_38" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, null, ["\n    "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](1, 0, null, null, 31, "free-fullpage", [], null, [["window", "resize"], ["document", "wheel"]], function (_v, en, $event) { var ad = true; if (("window:resize" === en)) {
        var pd_0 = (__WEBPACK_IMPORTED_MODULE_1__angular_core__["_29" /* ɵnov */](_v, 3).onResize() !== false);
        ad = (pd_0 && ad);
    } if (("document:wheel" === en)) {
        var pd_1 = (__WEBPACK_IMPORTED_MODULE_1__angular_core__["_29" /* ɵnov */](_v, 3).onWheel($event) !== false);
        ad = (pd_1 && ad);
    } return ad; }, __WEBPACK_IMPORTED_MODULE_2__component_fullpage_fullpage_component_ngfactory__["c" /* View_FullpageComponent_0 */], __WEBPACK_IMPORTED_MODULE_2__component_fullpage_fullpage_component_ngfactory__["a" /* RenderType_FullpageComponent */])), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_33" /* ɵprd */](512, null, __WEBPACK_IMPORTED_MODULE_3__component_common_dom__["a" /* DomRenderer */], __WEBPACK_IMPORTED_MODULE_3__component_common_dom__["a" /* DomRenderer */], [__WEBPACK_IMPORTED_MODULE_1__angular_core__["M" /* Renderer2 */]]), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_14" /* ɵdid */](3, 4374528, null, 0, __WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__["b" /* FullpageComponent */], [__WEBPACK_IMPORTED_MODULE_3__component_common_dom__["a" /* DomRenderer */]], { pagination: [0, "pagination"], paginationClickable: [1, "paginationClickable"] }, null), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n      "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](5, 0, null, 0, 5, "free-fullpage-slide", [], null, null, null, __WEBPACK_IMPORTED_MODULE_2__component_fullpage_fullpage_component_ngfactory__["d" /* View_FullpageSlideComponent_0 */], __WEBPACK_IMPORTED_MODULE_2__component_fullpage_fullpage_component_ngfactory__["b" /* RenderType_FullpageSlideComponent */])), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_14" /* ɵdid */](6, 49152, null, 0, __WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__["d" /* FullpageSlideComponent */], [__WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__["b" /* FullpageComponent */]], null, null), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n        "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](8, 0, null, 0, 1, "div", [["class", "fullpage"]], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](9, 0, null, null, 0, "img", [["alt", ""], ["src", "assets/images/f1.jpg"]], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n      "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n      "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](12, 0, null, 0, 5, "free-fullpage-slide", [], null, null, null, __WEBPACK_IMPORTED_MODULE_2__component_fullpage_fullpage_component_ngfactory__["d" /* View_FullpageSlideComponent_0 */], __WEBPACK_IMPORTED_MODULE_2__component_fullpage_fullpage_component_ngfactory__["b" /* RenderType_FullpageSlideComponent */])), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_14" /* ɵdid */](13, 49152, null, 0, __WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__["d" /* FullpageSlideComponent */], [__WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__["b" /* FullpageComponent */]], null, null), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n        "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](15, 0, null, 0, 1, "div", [["class", "fullpage"]], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](16, 0, null, null, 0, "img", [["alt", ""], ["src", "assets/images/f2.jpg"]], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n      "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n      "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](19, 0, null, 0, 5, "free-fullpage-slide", [], null, null, null, __WEBPACK_IMPORTED_MODULE_2__component_fullpage_fullpage_component_ngfactory__["d" /* View_FullpageSlideComponent_0 */], __WEBPACK_IMPORTED_MODULE_2__component_fullpage_fullpage_component_ngfactory__["b" /* RenderType_FullpageSlideComponent */])), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_14" /* ɵdid */](20, 49152, null, 0, __WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__["d" /* FullpageSlideComponent */], [__WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__["b" /* FullpageComponent */]], null, null), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n        "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](22, 0, null, 0, 1, "div", [["class", "fullpage"]], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](23, 0, null, null, 0, "img", [["alt", ""], ["src", "assets/images/f3.jpg"]], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n      "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n      "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](26, 0, null, 0, 5, "free-fullpage-slide", [], null, null, null, __WEBPACK_IMPORTED_MODULE_2__component_fullpage_fullpage_component_ngfactory__["d" /* View_FullpageSlideComponent_0 */], __WEBPACK_IMPORTED_MODULE_2__component_fullpage_fullpage_component_ngfactory__["b" /* RenderType_FullpageSlideComponent */])), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_14" /* ɵdid */](27, 49152, null, 0, __WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__["d" /* FullpageSlideComponent */], [__WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__["b" /* FullpageComponent */]], null, null), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n        "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](29, 0, null, 0, 1, "div", [["class", "fullpage"]], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](30, 0, null, null, 0, "img", [["alt", ""], ["src", "assets/images/f4.jpg"]], null, null, null, null, null)), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n      "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, 0, ["\n    "])), (_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_36" /* ɵted */](-1, null, ["\n  "]))], function (_ck, _v) { var currVal_0 = true; var currVal_1 = true; _ck(_v, 3, 0, currVal_0, currVal_1); }, null); }
function View_ReviewFullpageComponent_Host_0(_l) { return __WEBPACK_IMPORTED_MODULE_1__angular_core__["_38" /* ɵvid */](0, [(_l()(), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_15" /* ɵeld */](0, 0, null, null, 1, "free-review-fullpage", [], null, null, null, View_ReviewFullpageComponent_0, RenderType_ReviewFullpageComponent)), __WEBPACK_IMPORTED_MODULE_1__angular_core__["_14" /* ɵdid */](1, 49152, null, 0, __WEBPACK_IMPORTED_MODULE_5__review_fullpage_component__["a" /* ReviewFullpageComponent */], [], null, null)], null, null); }
var ReviewFullpageComponentNgFactory = __WEBPACK_IMPORTED_MODULE_1__angular_core__["_11" /* ɵccf */]("free-review-fullpage", __WEBPACK_IMPORTED_MODULE_5__review_fullpage_component__["a" /* ReviewFullpageComponent */], View_ReviewFullpageComponent_Host_0, {}, {}, []);



/***/ }),

/***/ "../../../../../src/app/democase/main-fullpage/review-fullpage.component.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return ReviewFullpageComponent; });
var ReviewFullpageComponent = (function () {
    function ReviewFullpageComponent() {
        this.pageTitle = 'Components-Fullpage';
    }
    return ReviewFullpageComponent;
}());



/***/ }),

/***/ "../../../../../src/app/democase/main-fullpage/review-fullpage.module.ngfactory.js":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "ReviewFullpageModuleNgFactory", function() { return ReviewFullpageModuleNgFactory; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__angular_core__ = __webpack_require__("../../../core/esm5/core.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__review_fullpage_module__ = __webpack_require__("../../../../../src/app/democase/main-fullpage/review-fullpage.module.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2__review_fullpage_component_ngfactory__ = __webpack_require__("../../../../../src/app/democase/main-fullpage/review-fullpage.component.ngfactory.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_3__angular_common__ = __webpack_require__("../../../common/esm5/common.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__ = __webpack_require__("../../../../../src/app/component/fullpage/fullpage.component.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_5__angular_router__ = __webpack_require__("../../../router/esm5/router.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_6__review_fullpage_routing__ = __webpack_require__("../../../../../src/app/democase/main-fullpage/review-fullpage-routing.ts");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_7__review_fullpage_component__ = __webpack_require__("../../../../../src/app/democase/main-fullpage/review-fullpage.component.ts");
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 








var ReviewFullpageModuleNgFactory = __WEBPACK_IMPORTED_MODULE_0__angular_core__["_12" /* ɵcmf */](__WEBPACK_IMPORTED_MODULE_1__review_fullpage_module__["a" /* ReviewFullpageModule */], [], function (_l) { return __WEBPACK_IMPORTED_MODULE_0__angular_core__["_26" /* ɵmod */]([__WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](512, __WEBPACK_IMPORTED_MODULE_0__angular_core__["k" /* ComponentFactoryResolver */], __WEBPACK_IMPORTED_MODULE_0__angular_core__["_8" /* ɵCodegenComponentFactoryResolver */], [[8, [__WEBPACK_IMPORTED_MODULE_2__review_fullpage_component_ngfactory__["a" /* ReviewFullpageComponentNgFactory */]]], [3, __WEBPACK_IMPORTED_MODULE_0__angular_core__["k" /* ComponentFactoryResolver */]], __WEBPACK_IMPORTED_MODULE_0__angular_core__["E" /* NgModuleRef */]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](4608, __WEBPACK_IMPORTED_MODULE_3__angular_common__["l" /* NgLocalization */], __WEBPACK_IMPORTED_MODULE_3__angular_common__["k" /* NgLocaleLocalization */], [__WEBPACK_IMPORTED_MODULE_0__angular_core__["A" /* LOCALE_ID */], [2, __WEBPACK_IMPORTED_MODULE_3__angular_common__["t" /* ɵa */]]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](512, __WEBPACK_IMPORTED_MODULE_3__angular_common__["b" /* CommonModule */], __WEBPACK_IMPORTED_MODULE_3__angular_common__["b" /* CommonModule */], []), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](512, __WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__["c" /* FullpageModule */], __WEBPACK_IMPORTED_MODULE_4__component_fullpage_fullpage_component__["c" /* FullpageModule */], []), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](512, __WEBPACK_IMPORTED_MODULE_5__angular_router__["n" /* RouterModule */], __WEBPACK_IMPORTED_MODULE_5__angular_router__["n" /* RouterModule */], [[2, __WEBPACK_IMPORTED_MODULE_5__angular_router__["s" /* ɵa */]], [2, __WEBPACK_IMPORTED_MODULE_5__angular_router__["k" /* Router */]]]), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](512, __WEBPACK_IMPORTED_MODULE_6__review_fullpage_routing__["a" /* ReviewFullpageRoutingModule */], __WEBPACK_IMPORTED_MODULE_6__review_fullpage_routing__["a" /* ReviewFullpageRoutingModule */], []), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](512, __WEBPACK_IMPORTED_MODULE_1__review_fullpage_module__["a" /* ReviewFullpageModule */], __WEBPACK_IMPORTED_MODULE_1__review_fullpage_module__["a" /* ReviewFullpageModule */], []), __WEBPACK_IMPORTED_MODULE_0__angular_core__["_27" /* ɵmpd */](1024, __WEBPACK_IMPORTED_MODULE_5__angular_router__["i" /* ROUTES */], function () { return [[{ path: "", component: __WEBPACK_IMPORTED_MODULE_7__review_fullpage_component__["a" /* ReviewFullpageComponent */] }]]; }, [])]); });



/***/ }),

/***/ "../../../../../src/app/democase/main-fullpage/review-fullpage.module.ts":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return ReviewFullpageModule; });
var ReviewFullpageModule = (function () {
    function ReviewFullpageModule() {
    }
    return ReviewFullpageModule;
}());



/***/ })

});
//# sourceMappingURL=review-fullpage.module.chunk.js.map